# Generated by Django 4.1.7 on 2024-01-09 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_student_options_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='teacher',
        ),
    ]
